export const PLAYER_INFO_ID = 'playerInfo'
export const PLAYER_HAND_ID = 'playerHand'
export const PLAYER_BOARD_ID = 'playerBoard'
export const PLAYER_DECK_ID = 'playerDeck'
export const PLAYER_DISCARD_ID = 'playerDiscard'

export const OPPONENT_INFO_ID = 'opponentInfo'
export const OPPONENT_HAND_ID = 'opponentHand'
export const OPPONENT_BOARD_ID = 'opponentBoard'
export const OPPONENT_DECK_ID = 'opponentDeck'
export const OPPONENT_DISCARD_ID = 'opponentDiscard'

export const CARD_TEST_ID = 'cardTestId'
export const OVERLAY_TEST_ID = 'overlayTestId'
export const MODAL_TEST_ID = 'modalTestId'
export const PANEL_TEST_ID = 'panelTestId'
