export const RegionNames = [
  'Eldermont',
  'Ravenshire',
  'Silverwood',
  'Crimsonburg',
  'Ironcrest',
  'Shadowhaven',
  'Moonstone Duchy',
  'Emberfall',
  'Thornwood',
  'Starhaven',
  'Ravenshadow',
  'Goldenhelm',
  'Stormwind',
  'Verdant Vale',
  'Wyvernwood',
  'Frostford',
  'Moonshadow Duchy',
  'Dragonspire',
  'Ravenshadow',
  'Celestial Domain'
]
